repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.0  # Or whatever version you prefer
  hooks:
    - id: clang-format
      types_or: [c++, c, cuda]  # Adjust file types as needed