<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheel_macros">

  <xacro:macro name="wheel" params="prefix width_in radius_in">

    <xacro:property name="m_per_in" value="${(1/12) * (1/3) * 0.9144}" />
    <xacro:property name="kg_per_lb" value="0.45359237" />

    <joint name="${prefix}_rotating_joint" type="continuous">
      <parent link="${prefix}_connector"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 0 ${radius_in*m_per_in}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${radius_in*m_per_in}" length="${width_in*m_per_in}"/>
        </geometry>
        <material name="Green">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${radius_in*m_per_in}" length="${width_in*m_per_in}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${10*kg_per_lb}"/>
        <inertia ixx="1.75e-5" ixy="0" ixz="0" iyy="1.75e-5" iyz="0" izz="1.75e-5"/>
      </inertial>
    </link>

  </xacro:macro>

  <xacro:macro name="wheel_connector" params="f r parent_link wheel_base_in track_width_in prefix">

    <xacro:property name="m_per_in" value="${(1/12) * (1/3) * 0.9144}" />
    <xacro:property name="kg_per_lb" value="0.45359237" />
    <xacro:property name="rad_per_deg" value="${pi/180}" />

    <xacro:if value="${f}">
      <xacro:if value="${r}">
        <joint name="${prefix}_connector_joint" type="revolute">
          <parent link="${parent_link}"/>
          <child link="${prefix}_connector"/>
          <origin xyz="${track_width_in*m_per_in/2} ${-wheel_base_in*m_per_in/2} 0" rpy="0 0 0"/>
          <limit effort="30" velocity="1.0" lower="${-47*rad_per_deg}" upper="${47*rad_per_deg}" />
          <axis xyz="0 0 1"/>
        </joint>
      </xacro:if>
      <xacro:unless value="${r}">
        <joint name="${prefix}_connector_joint" type="revolute">
          <parent link="${parent_link}"/>
          <child link="${prefix}_connector"/>
          <origin xyz="${track_width_in*m_per_in/2} ${wheel_base_in*m_per_in/2} 0" rpy="0 0 0"/>
          <limit effort="30" velocity="1.0" lower="${-47*rad_per_deg}" upper="${47*rad_per_deg}" />
          <axis xyz="0 0 1"/>
        </joint>
      </xacro:unless>
    </xacro:if>
    <xacro:unless value="${f}">
      <xacro:if value="${r}">
        <joint name="${prefix}_connector_joint" type="fixed">
          <parent link="${parent_link}"/>
          <child link="${prefix}_connector"/>
          <origin xyz="${-track_width_in*m_per_in/2} ${-wheel_base_in*m_per_in/2} 0" rpy="0 0 0"/>
        </joint>
      </xacro:if>
      <xacro:unless value="${r}">
        <joint name="${prefix}_connector_joint" type="fixed">
          <parent link="${parent_link}"/>
          <child link="${prefix}_connector"/>
          <origin xyz="${-track_width_in*m_per_in/2} ${wheel_base_in*m_per_in/2} 0" rpy="0 0 0"/>
        </joint>
      </xacro:unless>
      <gazebo reference="${prefix}_connector_joint">
        <disableFixedJointLumping>true</disableFixedJointLumping>
        <preserveFixedJoint>true</preserveFixedJoint>
      </gazebo>
    </xacro:unless>
  
    <link name="${prefix}_connector">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${kg_per_lb}"/>
        <inertia ixx="1.75e-5" ixy="0" ixz="0" iyy="1.75e-5" iyz="0" izz="1.75e-5"/>
      </inertial>
    </link>

  </xacro:macro>

</robot>