controller_manager:
  ros__parameters:
    update_rate: 100

    car_controller:
      type: ackermann_steering_controller/AckermannSteeringController

car_controller:
  ros__parameters:
    rear_wheels_names:
      - back_left_joint
      - back_right_joint
    front_wheels_names:
      - front_left_joint
      - front_right_joint