FROM debian:latest

# Update package lists
RUN apt update && \
    apt-get install -y build-essential git curl software-properties-common lsb-release make protobuf-compiler

RUN apt-get update && \
    apt-get upgrade -y

# Custom CMake install to get v3.28
ENV CMAKE_VERSION=3.28.1
RUN apt-get remove --purge --auto-remove -y cmake
RUN apt-get update && \
    apt-get -y install build-essential wget

RUN rm -rf /var/lib/apt/lists/*
RUN wget https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-linux-aarch64.sh \
      -q -O /tmp/cmake-install.sh
RUN chmod u+x /tmp/cmake-install.sh
RUN mkdir /opt/cmake-$CMAKE_VERSION
RUN /tmp/cmake-install.sh --skip-license --prefix=/opt/cmake-$CMAKE_VERSION
RUN rm /tmp/cmake-install.sh
RUN ln -s /opt/cmake-$CMAKE_VERSION/bin/* /usr/bin/

# Set up build and run scripts
WORKDIR /20xt_ws/

RUN printf "#!/bin/bash \
\ncmake -S /20xt_ws/src/base/ -B ./bin/ \
\ncmake --build ./bin/ \n" > ./build.sh

RUN printf "#!/bin/bash \
\n ./bin/data_logger > output.txt \
\n  \n" > ./run_programs.sh

RUN printf "#!/bin/bash" > ./run_tests.sh

# Start the workspace
CMD ["/bin/bash"]

