FROM ubuntu:22.04

# Update package lists
RUN apt update

# Install necessary packages
RUN apt-get install -y build-essential git curl software-properties-common lsb-release make protobuf-compiler
RUN apt-get update
RUN apt-get upgrade -y

# Custom CMake install to get v3.28
RUN apt-get remove --purge --auto-remove -y cmake
RUN apt-get update \
  && apt-get -y install build-essential \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/* \
  && wget https://github.com/Kitware/CMake/releases/download/v3.28.1/cmake-3.28.1-Linux-x86_64.sh \
      -q -O /tmp/cmake-install.sh \
      && chmod u+x /tmp/cmake-install.sh \
      && mkdir /opt/cmake-3.28.1 \
      && /tmp/cmake-install.sh --skip-license --prefix=/opt/cmake-3.28.1 \
      && rm /tmp/cmake-install.sh \
      && ln -s /opt/cmake-3.28.1/bin/* /usr/bin/

# Set the working directory
WORKDIR /20xt_ws/

# Start the workspace
CMD ["/bin/bash"]
