name: Combined ROS2 and ESP32-C3 Firmware Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ros:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./car
        file: ./car/docker/Dockerfile_car_ros
        push: false
        load: true
        tags: bjr_docker_ros:latest
        platforms: linux/arm64
    
    - name: Run build test in container
      run: |
        docker run --rm bjr_docker_ros:latest /bin/bash -c "/car/scripts/build_test.sh"

    - name: Store ROS Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ros-artifacts
        path: /car/build

  build_esp32:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: ESP-IDF build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32c3
        path: '20xt/firmware/esp_idf/prod/wsg_mqtt'

    - name: Archive ESP32 firmware
      uses: actions/upload-artifact@v2
      with:
        name: esp32-firmware
        path: 20xt/firmware/esp_idf/prod/wsg_mqtt/build/*.bin